### ISSUE TITLE
Message “detected as spam”

### ISSUE THREAD

**Issue by klodeckl** [derhansen/form_crshield#11]
Hi,
I feedback message “Your message was detected as spam” would be good instead of just displaying the form again when the form was submitted and detected as spam.

**Comment by derhansen** [comment]
I do not really understand, why the extension should display such a message. The purpose of the extension is to block automated form submissions by bots and I see no reason to notify a bot, that its form submission has been detected as spam. Can you explain the intention, why you would like to see such a message?

**Comment by schliesser** [comment]
@derhansen I fully agree with your answer!

**Comment by klodeckl** [comment]
I think about false positives. If a false positive occurs, the user could think that its message was submitted successfully.

**Comment by derhansen** [comment]
Again: The extensions purpose is to block spambots. To do so, JavaScript is required to calculate the value of a hidden input field. The extension is completely transparent to the user. The user submitted content is not analyzed for possible spam content (e.g. links or stop words), so there should really be no false positives at all and therefore also no message to show.
