### ISSUE TITLE
I always get different expected vs calculated data in Firefox 121 on mac

### ISSUE THREAD

**Issue by kaystrobach** [derhansen/form_crshield#20]
On Firefox:

https://github.com/derhansen/form_crshield/assets/1185776/ad061347-b183-4347-89cd-4896cf5085bd

Same form in chrome works:

https://github.com/derhansen/form_crshield/assets/1185776/f299c20f-86e9-4a18-a107-8f44c3cfb5fa

After some modifications the log contains this (for firefox):

```php
// Form.php line 82 ff to get better insight into debugging

        if ($calculatedData !== $clientData) {
            $this->logger->debug(
                'CR response missmatch. Submitted data',
                [
                    'calculatedData' => $calculatedData,
                    'expectedData' => $clientData
                ]
            );
            return '';
        }

```
Sat, 30 Dec 2023 15:28:02 +0100 [DEBUG] request="6c4e5ff2ae00d" component="Derhansen.FormCrshield.Hooks.Form": CR response missmatch. Submitted data - {"calculatedData":"8111n9r3sr0p5s4p4pr245052nr0669n57s285q9","expectedData":"8111a9e3fe0c5f4c4ce245052ae0669a57f285d9"}
```

And the js:

```javascript
// FormCrShield.js line 15 - the result was visible in the screencast

      console.log(element.value);
```

I doubt, some strange bug is causing a difference in the calculation of the javascript. Will try to reproduce that on a clean profile of firefox as well.

**Comment by kaystrobach** [comment]
It gets even weirder .. using the private mode it works, using the same profile with all extensions disabled (and restarted) it does not work). 

The interesting thing is that offset here:

```
calculatedData: 6o1181pr324o17684o4qq38103917p1rp69sr6r6
expectedData:   6b1181ce324b17684b4dd38103917c1ec69fe6e6
```

All the numbers are correct, but the characters are not. Is there a problem in the rot13 algorithm?

**Comment by derhansen** [comment]
I checked this on my Mac with Firefox 121.0, but I can not find any problems and the extension works as expected.

**Comment by kaystrobach** [comment]
Will try to reproduce it on another maschine, maybe a weird setting causes this problem.

**Comment by kaystrobach** [comment]
it's strange - after clearing all cookies 2 times it worked ... is there any requirement for caching - not chaching the form pages?

**Comment by kaystrobach** [comment]
it's weird. The one profile is not capable of sending the form.

This returns valid and reliably the same values ... 

```javascript
// var expiration = '1704046217';
// var challenge = 'e2eefaf40b02fa32f502ad52cac321e08c9d9266';

let [expiration,challenge,delay] = atob("MTcwNDA0NjIxN3xlMmVlZmFmNDBiMDJmYTMyZjUwMmFkNTJjYWMzMjFlMDhjOWQ5MjY2").split('|');

console.log(expiration);
console.log(challenge);

console.log(btoa(expiration + '|' + challenge.replace(/[a-z]/gi, char =>
{
  return String.fromCharCode( char.charCodeAt(0) + ( char.toUpperCase() <= 'M' ? 13 : -13 ) )
})));
```

**Comment by derhansen** [comment]
So only one profile in your Firefox is affected? I still can not reproduce the problem.

**Comment by kaystrobach** [comment]
seems so ... I also had a customer asking for the very same problem. After clearing cookies and resetting the local storage it seems to work now - very very strange. i would close this for now. I will try in the other instance later this month and provide some feedback.

**Comment by derhansen** [comment]
OK, I'll close this issue then. Feel free to comment to this issue in case you have additional findings in this regard.
