### ISSUE TITLE
Still a lot of Spam Mails

### ISSUE THREAD

**Issue by IvayloIvanov** [derhansen/form_crshield#30]
Hi there,

after installing the extension, many spam e-mails continue to arrive and pass the form_crsield protection.
When I inspect the formshield Log I noticed that many spam entries use the same value of the cr-field.

Here one example:

`Fri, 29 Nov 2024 12:02:07 +0100 [DEBUG] request="666b8860d1685" component="Derhansen.FormCrshield.Hooks.Form": Submitted data - {"salutation":"Herr","firstname":"Это реально: Wildberries дарит крутые призы. Попробуй - : https://docs.google.com/presentation/d/1MrRJ_Z0M0d9uONcNCD2qjnouqsSrgR7v5RWU2RLsg_4/preview","lastname":"Это реально: Wildberries дарит крутые призы. Попробуй - : https://docs.google.com/presentation/d/1MrRJ_Z0M0d9uONcNCD2qjnouqsSrgR7v5RWU2RLsg_4/preview","donorID":"Это реально: Wildberries дарит крутые призы. Попробуй - : https://docs.google.com/presentation/d/1MrRJ_Z0M0d9uONcNCD2qjnouqsSrgR7v5RWU2RLsg_4/preview","8VbfITe0kDRJsAmliXQOxyB":"Это реально: Wildberries дарит крутые призы. Попробуй - : https://docs.google.com/presentation/d/1MrRJ_Z0M0d9uONcNCD2qjnouqsSrgR7v5RWU2RLsg_4/preview","message":"Это реально: Wildberries дарит крутые призы. Попробуй - : https://docs.google.com/presentation/d/1MrRJ_Z0M0d9uONcNCD2qjnouqsSrgR7v5RWU2RLsg_4/preview","email":"olgapavlova22@gmail.com","cr-field":"MTczMjk1OTI4M3w2cnAxcTY5MzhyNDEzNW41bzkxNm82cTk0cTgzbjIzMDlubzVucjlu"}`

Current setup:
* TYPO3 11.5.42
* EXT:form_crshield 1.4.1
* Varnish, nginx, Apache2 stack

Any idea or suggestions?

Best regards
Ivaylo

**Comment by derhansen** [comment]
As stated in the docs, the protection can be bypassed (see https://github.com/derhansen/form_crshield?tab=readme-ov-file#can-the-protection-be-bypassed), if the bot supports JavaScript or if a human is filling out the form. One a valid cr-field is calculated, the response can be used multiple times. It however expires after some time depending on the page cache lifetime. 

So basically you can try to reduce the page cache lifetime for the page with the form and see, if this helps. But as previously stated, the extension targets spambots not using JavaScript, everything else may still pass.
