### ISSUE TITLE
[BUG] Form editor preview broken since install of form_crshield

### ISSUE THREAD

**Issue by klodeckl** [derhansen/form_crshield#9]
When the extension is installed, the preview in the form editor is broken. The following javascript error occurs:
Uncaught Error: Could not find form element "cr-field" in path "formName/page-1/cr-field" (1472424334)

If the extension is uninstalled it works.
TYPO3 10.4.32
PHP 7.4

**Comment by derhansen** [comment]
Thanks for your report. Actually, I did not even know there is a preview mode for forms. I pushed a bugfix with [1182117](https://github.com/derhansen/form_crshield/commit/1182117b86dddd5e021b4efba24a552aed790544), so the `cr-field` will not be added when the form is shown in preview mode or backend context.

**Comment by klodeckl** [comment]
Thank you, works!
